import { ArrowRight, Bot, Globe2, ShieldCheck, Sparkles, Zap } from "lucide-react";
import type { Region } from "@/data/contracts/gizway";

export type PublicCatalogModel = { name: string; family: string; description: string; price: string };
export type PublicCatalogProduct = { title: string; description: string; price: string };
export type PublicCatalogNotice = { id: "gizpay" | "gizway"; service: string; state: "first_sync" | "offline" | "empty" | "denied" | "sync_error"; message: string };

export function PublicHome({ region, models, products = [], notices = [], onSignIn }: { region: Region; models: PublicCatalogModel[]; products?: PublicCatalogProduct[]; notices?: PublicCatalogNotice[]; onSignIn?: () => void }) {
  return <main data-region={region} className="min-h-screen bg-app text-foreground">
    <header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
      <div className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl bg-brand text-white"><Zap className="size-5 fill-current" /></span><span className="text-lg font-bold">GizWay</span></div>
      <nav className="flex items-center gap-4"><a href="#catalog" className="text-sm text-muted-foreground">Model catalog</a>{onSignIn ? <button onClick={onSignIn} className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white">Sign in</button> : <a href="/auth/login" className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white">Sign in</a>}</nav>
    </header>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[1.15fr_.85fr] lg:pt-24">
      <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-brand/20 bg-brand-soft px-3 py-1.5 text-xs font-semibold text-brand"><Sparkles className="size-3.5" /> One gateway, many providers</div><h1 className="max-w-3xl text-5xl font-bold tracking-[-0.055em] sm:text-7xl">Multi-model AI gateway for builders.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Use leading AI models with one Subscription Key, transparent token pricing and regional execution.</p><div className="mt-8 flex gap-3">{onSignIn ? <button onClick={onSignIn} className="inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white">Sign in to start <ArrowRight className="size-4" /></button> : <a href="/auth/login" className="inline-flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white">Sign in to start <ArrowRight className="size-4" /></a>}<a href="#catalog" className="rounded-xl border border-border bg-card px-5 py-3 text-sm font-semibold">Browse models</a></div></div>
      <div className="grid content-center gap-4"><Feature icon={Globe2} title="Regional execution" text="Region-isolated providers and pricing." /><Feature icon={ShieldCheck} title="Private by design" text="Your Keys and account data stay in owner-only streams." /><Feature icon={Bot} title="OpenAI-compatible" text="Bring official SDKs and switch models without rewrites." /></div>
    </section>
    <section id="catalog" className="border-t border-border bg-card/40"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8">{notices.map((notice) => <div key={notice.id} role={notice.state === "denied" || notice.state === "sync_error" ? "alert" : "status"} data-testid={`public-${notice.id}-catalog-notice`} data-state={notice.state} className="mb-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-950"><strong>{notice.service}:</strong> {notice.message}</div>)}{products.map((product) => <article key={product.title} className="mb-10 rounded-2xl border border-brand/15 bg-brand-soft p-6"><p className="text-xs font-semibold uppercase tracking-[.15em] text-brand">GizWay service</p><h2 className="mt-2 text-2xl font-bold">{product.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{product.description}</p><p className="mt-3 text-xs font-semibold">{product.price}</p></article>)}<p className="text-xs font-semibold uppercase tracking-[.15em] text-brand">Model catalog</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Choose the right model for every call</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{models.map((model) => <article key={model.name} className="rounded-2xl border border-border bg-card p-6"><span className="text-xs font-semibold text-brand">{model.family}</span><h3 className="mt-2 text-lg font-bold">{model.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-muted-foreground">{model.description}</p><p className="mt-5 text-xs font-medium">{model.price}</p></article>)}</div></div></section>
  </main>;
}

function Feature({ icon: Icon, title, text }: { icon: typeof Bot; title: string; text: string }) {
  return <div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><Icon className="size-5 text-brand" /><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div>;
}
